name: Release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Package Managers
        run: npm i -g pnpm @dhruwlalan/opm
      - name: Install Dependencies
        run: opm ci
      - name: Run Tests
        run: opm test
  release:
    needs: test
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Package Managers
        run: npm i -g pnpm @dhruwlalan/opm
      - name: Install Dependencies
        run: opm ci
      - name: Semantic Release
        if: success()
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: dhruwlalan
          GIT_AUTHOR_EMAIL: dhruwlalan22@gmail.com
          GIT_COMMITTER_NAME: dhruwlalan
          GIT_COMMITTER_EMAIL: dhruwlalan22@gmail.com
