name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup Package Managers
        run: npm i -g pnpm only-package-manager
      - name: Install Dependencies
        run: opm ci
      - name: Run Tests
        run: opm test
